### ISSUE TITLE
Dragging the edges.

### ISSUE THREAD

**Issue by Axis4s** [sandeep-chahal/san-the-texture-ripper#11]
![image](https://user-images.githubusercontent.com/97393974/172454197-bbc6f36d-4942-4332-a292-27477a2bbfff.png)

whenever i try and select an edge to grab, it just keeps getting away from my cursor

**Comment by StomyPX** [comment]
I'm getting this too, it looks to me like the mouse cursor is being sampled from where it is on screen instead of where it is in the viewport.

**Comment by sandeep-chahal** [comment]
Hey guys, I have replaced d3 with konva to fix the this issue
